"""
    _jld2(path::String) -> Dict{String, Any}

Load a JLD2 file and return its contents as a dictionary.
"""
function _jld2(path::String)::Dict{String,Any}
    return load(path);
end

"""
    MyTestingMarketDataSet() -> Dict{String, Any}

Load S&P 500 daily OHLC data (Jan 3 2025 – Nov 18 2025) from a JLD2 file.
Data source: Polygon.io.
"""
function MyTestingMarketDataSet()
    path = joinpath(_PATH_TO_DATA, "SP500-Daily-OHLC-1-3-2025-to-11-18-2025.jld2");
    if isfile(path)
        return _jld2(path);
    else
        error("JLD2 data file not found at: $path\n" *
              "Please copy SP500-Daily-OHLC-1-3-2025-to-11-18-2025.jld2 into the data/ directory.\n" *
              "This file is generated by the CHEME-5660 course setup notebooks.");
    end
end

"""
    MyTrainingMarketDataSet() -> Dict{String, Any}

Load S&P 500 daily OHLC data (Jan 3 2014 – Dec 31 2024) from a JLD2 file.
Data source: Polygon.io.
"""
function MyTrainingMarketDataSet()
    path = joinpath(_PATH_TO_DATA, "SP500-Daily-OHLC-1-3-2014-to-12-31-2024.jld2");
    if isfile(path)
        return _jld2(path);
    else
        error("JLD2 data file not found at: $path\n" *
              "Please copy SP500-Daily-OHLC-1-3-2014-to-12-31-2024.jld2 into the data/ directory.");
    end
end

"""
    load_sagbm_parameters() -> DataFrame

Load the S&P 500 GBM parameters CSV containing precomputed drift and volatility
for each ticker. This can serve as a fallback when JLD2 market data is unavailable.
"""
function load_sagbm_parameters()::DataFrame
    path = joinpath(_PATH_TO_DATA, "SAGBM-Parameters-Fall-2025.csv");
    return CSV.read(path, DataFrame);
end

"""
    load_finviz_screener() -> DataFrame

Load the finviz screener CSV (pre-filtered for dividend yield > 3%).
Parses the Dividend Yield column from percentage strings to Float64.
"""
function load_finviz_screener()::DataFrame
    path = joinpath(_PATH_TO_DATA, "finviz.csv");
    df = CSV.read(path, DataFrame);

    df[!, :div_yield] = map(df[!, "Dividend Yield"]) do x
        s = replace(string(x), "%" => "")
        val = tryparse(Float64, s)
        return val === nothing ? 0.0 : val
    end

    return df;
end
